"""create audit 3nf tables

Revision ID: d9e63582e3e2
Revises: 358010f5f4cc
Create Date: 2026-03-15 20:20:47.684847

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9e63582e3e2"
down_revision: str | None = "358010f5f4cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("raw_line", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("epoch", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("serial", sa.Integer(), nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("uid", sa.Integer(), nullable=True),
        sa.Column("auid", sa.BigInteger(), nullable=True),
        sa.Column("ses", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.host_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("host_id", "line_number", name="uq_audit_event_host_line"),
    )
    op.create_table(
        "audit_avc_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("apparmor", sa.String(length=20), nullable=True),
        sa.Column("operation", sa.String(length=30), nullable=True),
        sa.Column("profile", sa.String(length=50), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("info", sa.Text(), nullable=True),
        sa.Column("comm", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["audit_event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "audit_login_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("old_auid", sa.BigInteger(), nullable=True),
        sa.Column("old_ses", sa.BigInteger(), nullable=True),
        sa.Column("tty", sa.String(length=30), nullable=True),
        sa.Column("res", sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["audit_event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "audit_message",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("op", sa.String(length=30), nullable=True),
        sa.Column("acct", sa.String(length=50), nullable=True),
        sa.Column("exe", sa.Text(), nullable=True),
        sa.Column("hostname", sa.String(length=50), nullable=True),
        sa.Column("addr", sa.String(length=50), nullable=True),
        sa.Column("terminal", sa.String(length=30), nullable=True),
        sa.Column("res", sa.String(length=20), nullable=True),
        sa.Column("unit", sa.String(length=100), nullable=True),
        sa.Column("comm", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("cwd", sa.Text(), nullable=True),
        sa.Column("cmd", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["audit_event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "audit_pam_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["audit_event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "audit_proctitle_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("proctitle", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["audit_event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "audit_service_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["audit_event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "audit_syscall_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("arch", sa.String(length=20), nullable=True),
        sa.Column("syscall", sa.Integer(), nullable=True),
        sa.Column("success", sa.String(length=5), nullable=True),
        sa.Column("exit", sa.BigInteger(), nullable=True),
        sa.Column("exe", sa.Text(), nullable=True),
        sa.Column("comm", sa.String(length=50), nullable=True),
        sa.Column("tty", sa.String(length=30), nullable=True),
        sa.Column("key", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["audit_event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "audit_user_cmd_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["audit_event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "audit_user_login_event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["audit_event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_user_login_event")
    op.drop_table("audit_user_cmd_event")
    op.drop_table("audit_syscall_event")
    op.drop_table("audit_service_event")
    op.drop_table("audit_proctitle_event")
    op.drop_table("audit_pam_event")
    op.drop_table("audit_message")
    op.drop_table("audit_login_event")
    op.drop_table("audit_avc_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
