"""create staging tables

Revision ID: ff2c88ab6174
Revises:
Create Date: 2026-03-13 20:09:07.185581

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff2c88ab6174"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stg_attack_label_line_raw",
        sa.Column("row_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_host", sa.String(length=30), nullable=False),
        sa.Column("source_log", sa.String(length=50), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("labels_json", sa.Text(), nullable=False),
        sa.Column("rules_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("row_id"),
    )
    op.create_table(
        "stg_audit_line_raw",
        sa.Column("row_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_host", sa.String(length=30), nullable=False),
        sa.Column("source_log", sa.String(length=50), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("raw_line", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("epoch", sa.Double(), nullable=False),
        sa.Column("serial", sa.Integer(), nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("uid", sa.Integer(), nullable=True),
        sa.Column("auid", sa.BigInteger(), nullable=True),
        sa.Column("ses", sa.BigInteger(), nullable=True),
        sa.Column("msg", sa.Text(), nullable=True),
        sa.Column("old_auid", sa.BigInteger(), nullable=True),
        sa.Column("old_ses", sa.BigInteger(), nullable=True),
        sa.Column("tty", sa.String(length=30), nullable=True),
        sa.Column("res", sa.String(length=10), nullable=True),
        sa.Column("apparmor", sa.String(length=20), nullable=True),
        sa.Column("operation", sa.String(length=30), nullable=True),
        sa.Column("info", sa.Text(), nullable=True),
        sa.Column("profile", sa.String(length=50), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("comm", sa.String(length=50), nullable=True),
        sa.Column("exe", sa.Text(), nullable=True),
        sa.Column("arch", sa.String(length=20), nullable=True),
        sa.Column("syscall", sa.Integer(), nullable=True),
        sa.Column("success", sa.String(length=5), nullable=True),
        sa.Column("exit", sa.BigInteger(), nullable=True),
        sa.Column("a0", sa.String(length=20), nullable=True),
        sa.Column("a1", sa.String(length=20), nullable=True),
        sa.Column("a2", sa.String(length=20), nullable=True),
        sa.Column("a3", sa.String(length=20), nullable=True),
        sa.Column("items", sa.Integer(), nullable=True),
        sa.Column("ppid", sa.Integer(), nullable=True),
        sa.Column("gid", sa.Integer(), nullable=True),
        sa.Column("euid", sa.Integer(), nullable=True),
        sa.Column("suid", sa.Integer(), nullable=True),
        sa.Column("fsuid", sa.Integer(), nullable=True),
        sa.Column("egid", sa.Integer(), nullable=True),
        sa.Column("sgid", sa.Integer(), nullable=True),
        sa.Column("fsgid", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=20), nullable=True),
        sa.Column("proctitle", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("row_id"),
    )
    op.create_table(
        "stg_host_raw",
        sa.Column("host_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("host_key", sa.String(length=50), nullable=False),
        sa.Column("hostname", sa.String(length=100), nullable=False),
        sa.Column("groups", sa.Text(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("openvpn_user", sa.String(length=50), nullable=True),
        sa.Column("distribution", sa.String(length=50), nullable=False),
        sa.Column("distribution_release", sa.String(length=20), nullable=False),
        sa.Column("distribution_version", sa.String(length=20), nullable=False),
        sa.Column("default_ipv4_address", sa.String(length=45), nullable=False),
        sa.Column("default_ipv6_address", sa.String(length=45), nullable=False),
        sa.Column("ipv4_addresses", sa.Text(), nullable=False),
        sa.Column("ipv6_addresses", sa.Text(), nullable=False),
        sa.Column("fqdns", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("host_id"),
        sa.UniqueConstraint("host_key"),
        sa.UniqueConstraint("hostname"),
    )
    op.create_table(
        "stg_host_log_config_raw",
        sa.Column("config_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("log_path", sa.Text(), nullable=False),
        sa.Column("log_type", sa.String(length=50), nullable=False),
        sa.Column("codec", sa.Text(), nullable=True),
        sa.Column("file_chunk_size", sa.Integer(), nullable=True),
        sa.Column("add_field_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["stg_host_raw.host_id"],
        ),
        sa.PrimaryKeyConstraint("config_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stg_host_log_config_raw")
    op.drop_table("stg_host_raw")
    op.drop_table("stg_audit_line_raw")
    op.drop_table("stg_attack_label_line_raw")
    # ### end Alembic commands ###
