"""create label 3nf tables

Revision ID: b4258b656aa5
Revises: d9e63582e3e2
Create Date: 2026-03-15 20:32:18.105433

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4258b656aa5"
down_revision: str | None = "d9e63582e3e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attack_phase",
        sa.Column("phase_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phase_name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("phase_id"),
        sa.UniqueConstraint("phase_name"),
    )
    op.create_table(
        "labeled_line",
        sa.Column("labeled_line_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_host", sa.String(length=30), nullable=False),
        sa.Column("source_log", sa.String(length=50), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("labeled_line_id"),
        sa.UniqueConstraint(
            "source_host", "source_log", "line_number", name="uq_labeled_line_provenance"
        ),
    )
    op.create_table(
        "attack_label",
        sa.Column("label_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("label_name", sa.String(length=80), nullable=False),
        sa.Column("phase_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["attack_phase.phase_id"],
        ),
        sa.PrimaryKeyConstraint("label_id"),
        sa.UniqueConstraint("label_name"),
    )
    op.create_table(
        "labeled_line_label",
        sa.Column("labeled_line_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["attack_label.label_id"],
        ),
        sa.ForeignKeyConstraint(
            ["labeled_line_id"], ["labeled_line.labeled_line_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("labeled_line_id", "label_id"),
    )
    op.create_table(
        "labeled_line_rule",
        sa.Column("labeled_line_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("rule_name", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["labeled_line_id"],
            ["labeled_line.labeled_line_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["labeled_line_id", "label_id"],
            ["labeled_line_label.labeled_line_id", "labeled_line_label.label_id"],
        ),
        sa.PrimaryKeyConstraint("labeled_line_id", "label_id", "rule_name"),
    )
    op.create_unique_constraint(
        "uq_stg_attack_label_line_raw_provenance",
        "stg_attack_label_line_raw",
        ["source_host", "source_log", "line_number"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_stg_attack_label_line_raw_provenance", "stg_attack_label_line_raw", type_="unique"
    )
    op.drop_table("labeled_line_rule")
    op.drop_table("labeled_line_label")
    op.drop_table("attack_label")
    op.drop_table("labeled_line")
    op.drop_table("attack_phase")
    # ### end Alembic commands ###
